name: PHP FPM Full

on:
  workflow_dispatch:
    inputs:
      from:
        description: "Tag to pull"
        default: '7.4-deb'
        required: true
      to:
        description: "Tag to push"
        default: '7.4-deb'
        required: true

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: images/php-fpm/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_TAG=${{ github.event.inputs.from }}
          tags: |
            ghcr.io/oreales/warden-php:${{ github.event.inputs.to }}
            ghcr.io/oreales/warden-php:latest
  php-m2:
    runs-on: ubuntu-latest
    needs: php
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/magento2
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_TAG=${{ github.event.inputs.from }}
          tags: |
            ghcr.io/oreales/warden-php-m2:${{ github.event.inputs.to }}
            ghcr.io/oreales/warden-php-m2:latest
  php-m2-xdebug3:
    runs-on: ubuntu-latest
    needs: [php, php-m2]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: images/php-fpm/magento2/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_TAG=${{ github.event.inputs.from }}
          tags: |
            ghcr.io/oreales/warden-php-m2-xdebug3:${{ github.event.inputs.to }}
            ghcr.io/oreales/warden-php-m2-xdebug3:latest
