name: PHP for M2 with xDebug

on:
  workflow_dispatch:
    inputs:
      from:
        description: "Tag to pull"
        default: '7.4-deb'
        required: true
      to:
        description: "Tag to push"
        default: '7.4-deb'
        required: true
      xdebug:
        description: "XDebug version"
        default: '3'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: images/php-fpm/magento2/xdebug${{ github.event.inputs.xdebug }}/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_TAG=${{ github.event.inputs.from }}
          tags: |
            ghcr.io/oreales/warden-php-m2-xdebug${{ github.event.inputs.xdebug }}:${{ github.event.inputs.to }}
            ghcr.io/oreales/warden-php-m2-xdebug${{ github.event.inputs.xdebug }}:latest
