name: Nginx

on:
  workflow_dispatch:
    inputs:
      nginx18:
        description: "nginx 1.18 (latest)"
        default: '0'
        required: false
      nginx17:
        description: "nginx 1.17"
        default: '0'
        required: false
      nginx16:
        description: "nginx 1.16"
        default: '0'
        required: false

jobs:
  nginx18:
    if: ${{ github.event.inputs.nginx18 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/nginx/context
          file: images/nginx/1.18/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gabriel0702usesi/nginx-multi-arch:1.18
            ghcr.io/oreales/warden-nginx:1.18
            ghcr.io/oreales/warden-nginx:latest
  nginx17:
    if: ${{ github.event.inputs.nginx17 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/nginx/context
          file: images/nginx/1.17/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gabriel0702usesi/nginx-multi-arch:1.17
            ghcr.io/oreales/warden-nginx:1.17
  nginx16:
    if: ${{ github.event.inputs.nginx18 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/nginx/context
          file: images/nginx/1.16/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gabriel0702usesi/nginx-multi-arch:1.16
            ghcr.io/oreales/warden-nginx:1.16
